# Generated by Django 4.0.4 on 2022-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateField()),
                ('num_pages', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateField()),
                ('type', models.CharField(choices=[(1, 'Bullet'), (2, 'Food'), (3, 'Travel'), (4, 'Sport')], max_length=10)),
                ('publisher', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'db_table': 'journals',
                'ordering': ['id'],
            },
        ),
    ]
