# Generated by Django 4.0.4 on 2022-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('Bullet', 1), ('Food', 2), ('Travel', 3), ('Sport', 4)], max_length=10),
        ),
    ]
