# Generated by Django 4.0.4 on 2022-05-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoreuser',
            name='roles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.userroles'),
        ),
    ]
