# Generated by Django 4.0.4 on 2022-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bookstoreuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoreuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
